### ISSUE TITLE
undesirable color convertsion to YCbCr with X2RGB10 (A2RGB10)

### ISSUE THREAD

**Issue by MartinPulec** [intel/cartwheel-ffmpeg#222] opened 2023-01-23 14:22 UTC
Hi, I'm encountering a problem with patched FFmpeg and oneVPL when using pixel format X2RGB10/A2RGB10. Something is performing unwanted RGB->YUV conversion but pretending that the output stream is in RGB. I'd like to have a 10-bit RGB HEVC, anyways. Steps to reproduce:

    ffmpeg -f lavfi -i smptebars -pix_fmt x2rgb10le -t 1 -c:v hevc_qsv rgb10.mp4
    ffplay rgb10.mp4    # <- colors are shifted here; it has been converted to YUV but displayed as RGB
    # mediainfo '--Output=Video;%ColorSpace%' rgb10.mp4  # confirms RGB

I am using this repo submodule FFmpeg with patches applied. iGPU is the one integrated on _Intel i7-1260P_. Upstream graphics libraries are installed [as described here](https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-legacy.html).

I've tried also "_bgra_" pixfmt but it says it is unsupported. _vuyx_ and _xv30le_ were OK (but encoding YCbCr obviously).

**Comment by MartinPulec** [comment] 2023-01-24 08:39
Just for illustration how it should look:

![correct](https://user-images.githubusercontent.com/9962268/214245960-78a1a338-1707-41c7-9650-43aa26e8e905.png)

and how the output actually looks:

![incorrect](https://user-images.githubusercontent.com/9962268/214245983-1742067a-5f15-4826-b25f-9e28772d3238.png)

**Comment by MartinPulec** [comment] 2023-02-01 13:40
AFAIK, the opposite problem holds also for _hevc\_qsv_ decoder - if input HEVC stream is a RGB, the decoder decompresses the data depending on bit-depth into XV36 or VUYX pixfmt (thus YCbCr) but no actual color conversion happens. The decompressed data are original RGB but presented in YCbCr pixel format.

**Comment by xhaihao** [comment] 2023-02-06 06:15
> I've tried also "bgra" pixfmt but it says it is unsupported.

bgra should be supported but you should boot your Linux kernel with HuC support.  According to https://github.com/intel/media-driver/blob/master/docs/media_features.md#supported-encoding-input-format-and-max-resolution,  HuC is required for RGB input.

**Comment by MartinPulec** [comment] 2023-02-06 15:19
Thanks a lot, I didn't know about this stuff at all, I'll give it a try.

Anyways, perhaps more interesting for our users would to keep/compress 10-bit RGB directly, without CS conversion - should it work? The rightmost column of [this table](https://github.com/intel/media-driver/blob/master/docs/media_features.md#supported-video-processing-cscscaling-format) says 'N' for all "Inputs'. But if Input means encode, it contradicts what I've seen - the RGB->YUV conversion was actually performed, but the stream itself identifies as internally RGB.

**Comment by wenbinc-Bin** [comment] 2023-02-07 07:15
I can reproduce the problem and I am working on it.

**Comment by MartinPulec** [comment] 2023-02-07 15:08
@wenbinc-Bin thanks a lot!

@xhaihao I can confirm that 8-bit RGB (bgra) works correctly in the HuC mode with patched FFmpeg when set `AVCodecContext::low_power == 1`.

**Comment by wenbinc-Bin** [comment] 2023-02-08 03:15
The cause is that ffmpeg pass sRGB in MatrixCoefficient to VPL but VPL doesn't encode video as RGB. It convert frame to YUV. However VPL still set this flag in stream header. FFmpeg will treat this stream as RGB but actually it is YUV.

**Comment by alatteri** [comment] 2023-02-09 01:49
Hi @wenbinc-Bin  .... I'm not sure from your reply if this is something your team is going to be able to fix or not.
Thanks.

> The cause is that ffmpeg pass sRGB in MatrixCoefficient to VPL but VPL doesn't encode video as RGB. It convert frame to YUV. However VPL still set this flag in stream header. FFmpeg will treat this stream as RGB but actually it is YUV.

**Comment by wenbinc-Bin** [comment] 2023-02-09 01:51
I will submit patch to fix this.

**Comment by wenbinc-Bin** [comment] 2023-02-13 06:01
I submitted a patch to upstream: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230213055545.535005-1-wenbin.chen@intel.com/

**Comment by MartinPulec** [comment] 2023-02-13 08:34
Great, thanks for that. I've quickly tested it and it works, the that encoded stream has now correct colors when decoded. Not a big deal but I guess that comment in patch is inverted (RGB gets converted to YCbCr, not vice versa)?

**Comment by wenbinc-Bin** [comment] 2023-02-13 08:38
Thank you for pointing it out.

**Comment by wenbinc-Bin** [comment] 2023-02-20 08:10
patch is merged: [https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230213084926.543371-1-wenbin.chen@intel.com/](https://patchwork.ffmpeg.org/project/ffmpeg/patch/20230213084926.543371-1-wenbin.chen@intel.com/).

**Closed** 2023-03-02 05:44 UTC
